name: Build and Deploy API

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      # Create .env file dynamically
      - name: Create .env File
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "GOOGLE_CLOUD_IP=${{ secrets.GOOGLE_CLOUD_IP }}" >> .env
          echo "GOCARDLESS_ID=${{ secrets.GOCARDLESS_ID }}" >> .env
          echo "GOCARDLESS_KEY=${{ secrets.GOCARDLESS_KEY }}" >> .env
          echo "GOCARDLESS_ACCOUNT_ID=${{ secrets.GOCARDLESS_ACCOUNT_ID }}" >> .env

      # Verify the .env file (optional for debugging)
      - name: Verify .env File
        run: cat .env

      # Publish .NET Application (Debug)
      - name: Publish .NET Application (Debug)
        run: dotnet publish BankoApi/BankoApi.csproj -c Debug -o publish

      # Build Docker Image
      - name: Build Docker Image
        run: docker build --build-arg CONFIGURATION=Debug -t ${{ secrets.DOCKER_USERNAME }}/banko-api-dev:${{ github.sha }} .

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/banko-api-dev:${{ github.sha }}

      # Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Upload the .env file to the server
            echo "DB_USER=${{ secrets.DB_USER }}" > /home/${{ secrets.SERVER_USER }}/.env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> /home/${{ secrets.SERVER_USER }}/.env
            echo "GOOGLE_CLOUD_IP=${{ secrets.GOOGLE_CLOUD_IP }}" >> /home/${{ secrets.SERVER_USER }}/.env
            echo "GOCARDLESS_ID=${{ secrets.GOCARDLESS_ID }}" >> /home/${{ secrets.SERVER_USER }}/.env
            echo "GOCARDLESS_KEY=${{ secrets.GOCARDLESS_KEY }}" >> /home/${{ secrets.SERVER_USER }}/.env
            echo "GOCARDLESS_ACCOUNT_ID=${{ secrets.GOCARDLESS_ACCOUNT_ID }}" >> /home/${{ secrets.SERVER_USER }}/.env

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/banko-api-dev:${{ github.sha }}

            # Stop and remove the existing container (if any)
            docker stop banko-api-dev || true
            docker rm banko-api-dev || true

            # Run the container with the .env file
            docker run -d -p 5119:8080 --env-file /home/${{ secrets.SERVER_USER }}/.env --name banko-api-dev \
              ${{ secrets.DOCKER_USERNAME }}/banko-api-dev:${{ github.sha }}
