name: Build and Deploy API to PROD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0 # Use your desired .NET version

      # Step 3: Create the .env file dynamically
      - name: Create .env File
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASSWORD }}" >> .env
          echo "GOOGLE_CLOUD_IP=${{ secrets.GOOGLE_CLOUD_IP }}" >> .env
          echo "GOCARDLESS_ID=${{ secrets.GOCARDLESS_ID }}" >> .env
          echo "GOCARDLESS_KEY=${{ secrets.GOCARDLESS_KEY }}" >> .env
          echo "GOCARDLESS_ACCOUNT_ID=${{ secrets.GOCARDLESS_ACCOUNT_ID }}" >> .env

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build --build-arg ENV_FILE=.env --build-arg CONFIGURATION=Debug -t setzener/banko-api:release .


      # Step 5: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push Docker Image
      - name: Push Docker Image
        run: docker push banko-api:${{ github.sha }}

      # Step 7: Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull banko-api:${{ github.sha }}
            docker stop banko-api-container || true
            docker rm banko-api-container || true
            docker run -d -p 5002:80 --name banko-api-container banko-api:${{ github.sha }}